language: python
sudo: required
python:
  - 3.6.4
before_install: 
  - pip install serial
install: 
  - "pip install --upgrade pip && pip install -r requirements.txt"
  - pip install serial
script:
  - python .//source//bt_hci_cmd_test_wc.py
